# Generated by Django 2.1.2 on 2018-10-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'managed': False, 'ordering': ('id', 'a')},
        ),
    ]
