# Generated by Django 2.1.2 on 2018-10-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_editor', '0002_auto_20181005_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'managed': False},
        ),
    ]
